/**
 * 後台可編輯的學生端文案鍵（與後端 siteContentManifest 前綴規則對齊）
 */
import { EMI_ADMIN_STAFF, EMI_FACULTY } from '../data/emiCenterStaff';

export const SITE_CONTENT_SECTIONS = [
  { id: 'home', label: '首頁' },
  { id: 'activities', label: '活動介紹' },
  { id: 'about', label: '關於我們' },
  { id: 'contact', label: '聯絡我們' },
  { id: 'legal', label: '隱私權／使用條款' },
  { id: 'faq', label: '常見問題' },
  { id: 'rules_modal', label: '活動規定／FAQ 彈窗' },
  { id: 'staff_faculty', label: '師資名單' },
  { id: 'staff_admin', label: '行政團隊' },
];

export const STRUCTURED_SECTIONS = ['faq', 'staff_faculty', 'staff_admin'];

export const SITE_CONTENT_KEY_SUGGESTIONS = {
  home: [
    { key: 'homePage.heroEyebrow', label: 'Hero 副標' },
    { key: 'homePage.heroTitle', label: 'Hero 主標題' },
    { key: 'homePage.heroDesc', label: 'Hero 說明' },
    { key: 'homePage.heroServices', label: 'Hero 服務摘要' },
    { key: 'homePage.coreTasksTitle', label: '核心任務標題' },
    { key: 'homePage.coreTasksLead', label: '核心任務說明' },
    { key: 'homePage.activitiesTitle', label: '近期活動區塊標題' },
    { key: 'homePage.activitiesLead', label: '近期活動區塊說明' },
    { key: 'homePage.stepsTitle', label: '使用流程標題' },
    { key: 'homePage.announcementsTitle', label: '公告區塊標題' },
    { key: 'homePage.announcementsLead', label: '公告區塊說明' },
    { key: 'homePage.faqTitle', label: 'FAQ 區塊標題' },
    { key: 'home.noticeSurveyBefore', label: '問卷提醒（前段）' },
    { key: 'home.ruleNoStamp', label: '不補蓋章規定' },
    { key: 'home.ruleNoWalkIn', label: '不開放現場候補' },
  ],
  activities: [
    { key: 'activitiesPage.title', label: '頁面標題' },
    { key: 'activitiesPage.overviewLead', label: '頁面導言' },
    { key: 'activitiesPage.catalogLead', label: '活動類型說明' },
    { key: 'activitiesPage.scheduleLead', label: '時間整理說明' },
    { key: 'activities.etDesc', label: 'English Table 簡介' },
    { key: 'activities.ecDesc', label: 'English Club 簡介' },
    { key: 'activities.ifDesc', label: 'International Forum 簡介' },
    { key: 'activities.jtDesc', label: 'Job Talk 簡介' },
    { key: 'page.activitiesLead', label: '活動總覽導言' },
  ],
  about: [
    { key: 'aboutPage.eearsIntro', label: 'EEARS 系統介紹' },
    { key: 'aboutPage.centerIntro', label: 'EMI 中心介紹' },
    { key: 'aboutPage.facultyLead', label: '師資區塊說明' },
    { key: 'aboutPage.adminLead', label: '行政團隊說明' },
  ],
  contact: [
    { key: 'homePage.contactTitle', label: '聯絡頁標題' },
    { key: 'homePage.contactLead', label: '聯絡頁導言' },
    { key: 'homePage.contactAddressValue', label: '地址' },
    { key: 'homePage.contactPhoneValue', label: '電話' },
    { key: 'homePage.contactEmailValue', label: 'Email' },
    { key: 'homePage.contactHoursValue', label: '服務時間' },
  ],
  legal: [
    { key: 'privacyPage.lastUpdated', label: '隱私權最後更新' },
    { key: 'privacyPage.intro', label: '隱私權前言' },
    { key: 'termsPage.lastUpdated', label: '使用條款最後更新' },
    { key: 'termsPage.intro', label: '使用條款前言' },
  ],
  rules_modal: [
    { key: 'faq.title', label: '彈窗標題' },
    { key: 'faq.cancel', label: 'Tab：取消預約' },
    { key: 'faq.blacklist', label: 'Tab：黑名單' },
    { key: 'faq.rules', label: 'Tab：活動規定' },
    { key: 'faq.cancelQuestion', label: '取消預約標題' },
    { key: 'faq.cancelSteps', label: '取消步驟標題' },
    { key: 'faq.cancelStep1', label: '取消步驟 1' },
    { key: 'faq.cancelStep2', label: '取消步驟 2' },
    { key: 'faq.cancelStep3', label: '取消步驟 3' },
    { key: 'faq.cancelStep4', label: '取消步驟 4' },
    { key: 'faq.cancelStep5', label: '取消步驟 5' },
    { key: 'faq.importantReminder', label: '重要提醒標題' },
    { key: 'faq.cancelRemind1', label: '取消提醒 1' },
    { key: 'faq.cancelRemind2', label: '取消提醒 2' },
    { key: 'faq.cancelRemind3', label: '取消提醒 3' },
    { key: 'faq.cancelRemind4', label: '取消提醒 4' },
    { key: 'faq.blacklistQuestion', label: '黑名單標題' },
    { key: 'faq.blacklistMechanism', label: '黑名單機制' },
    { key: 'faq.blacklistRule', label: '黑名單規則' },
    { key: 'faq.violationsInclude', label: '違規行為標題' },
    { key: 'faq.violation1', label: '違規 1' },
    { key: 'faq.violation2', label: '違規 2' },
    { key: 'faq.violation3', label: '違規 3' },
    { key: 'faq.blacklistImpact', label: '黑名單影響標題' },
    { key: 'faq.impact1', label: '影響 1' },
    { key: 'faq.impact2', label: '影響 2' },
    { key: 'faq.impact3', label: '影響 3' },
    { key: 'faq.impact4', label: '影響 4' },
    { key: 'faq.howToAvoid', label: '如何避免標題' },
    { key: 'faq.avoid1', label: '避免 1' },
    { key: 'faq.avoid2', label: '避免 2' },
    { key: 'faq.avoid3', label: '避免 3' },
    { key: 'faq.avoid4', label: '避免 4' },
    { key: 'faq.avoid5', label: '避免 5' },
    { key: 'faq.rulesTitle', label: '活動規定標題' },
    { key: 'faq.rulesImportant', label: '重要規定' },
    { key: 'faq.ruleNoOnsite', label: '不接受現場預約（摘要）' },
    { key: 'faq.ruleNoStampService', label: '不補蓋章（摘要）' },
    { key: 'faq.ruleNoLate5', label: '不接受遲到（摘要）' },
    { key: 'faq.ruleNoOnsiteDetail', label: '現場預約細項標題' },
    { key: 'faq.ruleNoOnsiteD1', label: '現場預約細項 1' },
    { key: 'faq.ruleNoOnsiteD2', label: '現場預約細項 2' },
    { key: 'faq.ruleNoOnsiteD3', label: '現場預約細項 3' },
    { key: 'faq.ruleNoOnsiteD4', label: '現場預約細項 4' },
    { key: 'faq.ruleNoStampDetail', label: '補蓋章細項標題' },
    { key: 'faq.ruleNoStampD1', label: '補蓋章細項 1' },
    { key: 'faq.ruleNoStampD2', label: '補蓋章細項 2' },
    { key: 'faq.ruleNoStampD3', label: '補蓋章細項 3' },
    { key: 'faq.ruleNoStampD4', label: '補蓋章細項 4' },
    { key: 'faq.ruleLateDetail', label: '遲到細項標題' },
    { key: 'faq.ruleLateD1', label: '遲到細項 1' },
    { key: 'faq.ruleLateD2', label: '遲到細項 2' },
    { key: 'faq.ruleLateD3', label: '遲到細項 3' },
    { key: 'faq.ruleLateD4', label: '遲到細項 4' },
    { key: 'faq.ruleLateD5', label: '遲到細項 5' },
    { key: 'faq.otherRules', label: '其他規定標題' },
    { key: 'faq.otherR1', label: '其他規定 1' },
    { key: 'faq.otherR2', label: '其他規定 2' },
    { key: 'faq.otherR3', label: '其他規定 3' },
    { key: 'faq.otherR4', label: '其他規定 4' },
    { key: 'faq.otherR5', label: '其他規定 5' },
  ],
};

function mapStaffSeed(members) {
  return members.map((m) => ({
    slug: m.id,
    label: m.name.zh,
    nameZh: m.name.zh,
    nameEn: m.name.en,
    roleZh: m.role.zh,
    roleEn: m.role.en,
    email: m.email || null,
    extension: m.extension || null,
  }));
}

export const DEFAULT_STAFF_SEED = {
  staff_faculty: mapStaffSeed(EMI_FACULTY),
  staff_admin: mapStaffSeed(EMI_ADMIN_STAFF),
};

export const DEFAULT_FAQ_SEED = [
  {
    label: '如何預約活動',
    questionZh: '我要怎麼預約活動？',
    questionEn: 'How do I reserve an activity?',
    answerZh: '點選「立即預約活動」進入日曆頁，選擇開放預約中的場次，再依畫面填寫姓名、學號與信箱。送出後請確認系統提示與信箱通知，活動當天依公告時間到場。',
    answerEn: 'Click "Book an Activity" to open the calendar, choose an open session, then enter your name, student ID, and email. Confirm the on-screen message and email notification, and arrive on time.',
  },
  {
    label: '如何選擇活動類型',
    questionZh: '我還不確定要參加哪一種活動，該怎麼選？',
    questionEn: 'How do I choose the right activity type?',
    answerZh: '可以先到「活動介紹」查看各活動差異。想練課堂主題可選 English Table；想增加口說練習可選 English Club；想和國際學生交流可選 International Forum；想準備面試或職場英文可選 Job Talk。',
    answerEn: 'Visit Activities to compare formats. English Table for course topics, English Club for speaking practice, International Forum for cross-cultural exchange, and Job Talk for career English.',
  },
  {
    label: '取消預約',
    questionZh: '無法出席時可以取消預約嗎？',
    questionEn: 'Can I cancel if I cannot attend?',
    answerZh: '可以。請在活動開始前 2 小時到「查詢／取消我的預約」輸入姓名、學號與信箱，找到該筆預約後取消。若未取消且未到場，會被記為違規。',
    answerEn: 'Yes. At least 2 hours before the session starts, go to My Reservations, enter your details, and cancel. No-shows without cancellation count as violations.',
  },
  {
    label: '問卷要求',
    questionZh: '為什麼有些活動需要先完成問卷？',
    questionEn: 'Why is a survey required for some activities?',
    answerZh: '部分 English Table 或 English Club 場次會要求先完成本學期問卷，中心會用問卷確認學生背景與活動需求。若系統提示需填問卷，請先完成後再回到日曆預約。',
    answerEn: 'Some English Table or English Club sessions require the semester survey first. Complete it when prompted, then return to book.',
  },
  {
    label: '額滿與候補',
    questionZh: '活動額滿時還能預約嗎？',
    questionEn: 'What if a session is full?',
    answerZh: '若場次已額滿，系統會依該活動設定顯示是否可候補或暫停預約。建議先查看其他同類型場次，也可以留意最新公告與日曆是否新增場次。',
    answerEn: 'If a session is full, the system may offer waitlist or block booking depending on settings. Try another session or watch for new openings in announcements.',
  },
  {
    label: '違規紀錄',
    questionZh: '違規紀錄會怎麼計算？',
    questionEn: 'How are violations counted?',
    answerZh: '常見違規包含成功預約但未到場、遲到超過規定時間、活動中無故離席等。同一學期累積兩次違規會被列入黑名單兩週，期間無法預約活動。',
    answerEn: 'Violations include no-shows, late arrival beyond the allowed window, and leaving without permission. Two violations in one semester trigger a two-week booking blacklist.',
  },
  {
    label: '學習紀錄',
    questionZh: '參加活動後會有學習紀錄或證明嗎？',
    questionEn: 'Will I get learning records or certification?',
    answerZh: '活動完成後的紀錄會依中心規則處理。若要申請英語實踐歷程或能力認證，請到「英語實踐歷程護照」查看可申請項目、上傳資料與審核狀態。',
    answerEn: 'Records follow center policy after attendance. For English Learning Passport certification, check eligible items and submission status there.',
  },
  {
    label: '英檢與活動預約',
    questionZh: '培力英檢報名和活動預約是同一件事嗎？',
    questionEn: 'Is BESTEP registration the same as activity booking?',
    answerZh: '不是。活動預約主要用於 English Table、English Club、International Forum、Job Talk 等活動；培力英檢報名是另一個流程，請從「培力英檢報名」入口進入。',
    answerEn: 'No. Activity booking is for English Table, Club, Forum, and Job Talk. BESTEP registration is a separate flow from the BESTEP entry point.',
  },
];
