'use strict';

const READ_ALOUD_TASKS = [
  {
    taskKey: 'ra-a2-campus-library',
    level: 'A2',
    taskType: 'read_aloud',
    title: 'Campus Library',
    prompt: 'Read the sentence aloud clearly.',
    targetText: 'The university library is quiet, and many students study there after class.',
    estimatedSeconds: 12,
    targetWords: 13,
    focusTags: ['campus', 'word_completion', 'sentence_stress'],
    constructTags: ['fluency', 'pronunciation_intelligibility', 'task_achievement'],
  },
  {
    taskKey: 'ra-a2-club-meeting',
    level: 'A2',
    taskType: 'read_aloud',
    title: 'Club Meeting',
    prompt: 'Read the sentence aloud clearly.',
    targetText: 'Our English club meets every Wednesday afternoon in the student center.',
    estimatedSeconds: 11,
    targetWords: 11,
    focusTags: ['campus', 'rhythm', 'final_consonants'],
    constructTags: ['fluency', 'pronunciation_intelligibility', 'task_achievement'],
  },
  {
    taskKey: 'ra-b1-group-project',
    level: 'B1',
    taskType: 'read_aloud',
    title: 'Group Project',
    prompt: 'Read the sentence aloud clearly.',
    targetText: 'When our group project became difficult, we divided the work and met twice a week.',
    estimatedSeconds: 14,
    targetWords: 15,
    focusTags: ['past_tense', 'consonant_clusters', 'pausing'],
    constructTags: ['fluency', 'pronunciation_intelligibility', 'grammar'],
  },
  {
    taskKey: 'ra-b1-international-activity',
    level: 'B1',
    taskType: 'read_aloud',
    title: 'International Activity',
    prompt: 'Read the sentence aloud clearly.',
    targetText: 'Students can improve their confidence by joining international activities and speaking with visitors.',
    estimatedSeconds: 14,
    targetWords: 12,
    focusTags: ['linking', 'sentence_stress', 'campus'],
    constructTags: ['fluency', 'pronunciation_intelligibility', 'vocabulary'],
  },
  {
    taskKey: 'ra-b2-learning-environment',
    level: 'B2',
    taskType: 'read_aloud',
    title: 'Learning Environment',
    prompt: 'Read the sentence aloud clearly.',
    targetText: 'A supportive learning environment can increase motivation, especially when students receive specific feedback.',
    estimatedSeconds: 16,
    targetWords: 13,
    focusTags: ['academic_vocabulary', 'stress', 'prosody'],
    constructTags: ['fluency', 'pronunciation_intelligibility', 'vocabulary'],
  },
  {
    taskKey: 'ra-b2-policy-discussion',
    level: 'B2',
    taskType: 'read_aloud',
    title: 'Policy Discussion',
    prompt: 'Read the sentence aloud clearly.',
    targetText: 'Although online courses are convenient, face-to-face discussion often helps students develop stronger arguments.',
    estimatedSeconds: 17,
    targetWords: 13,
    focusTags: ['complex_clause', 'rhythm', 'academic_discussion'],
    constructTags: ['fluency', 'pronunciation_intelligibility', 'grammar'],
  },
];

module.exports = {
  READ_ALOUD_TASKS,
};
