'use strict';

/** @typedef {{ name: string, description?: string, required?: boolean }} EmailVarDef */

/**
 * 系統郵件模板目錄（SSOT：key 必須與 config/email.js 的 emailTemplates 一致）
 * 變數以 {{name}} 寫在覆寫主旨／正文中；未覆寫時仍走程式預設。
 */
const EMAIL_TEMPLATE_CATALOG = [
  {
    key: 'reservationSuccess',
    category: 'reservation',
    categoryLabel: '活動預約',
    name: '預約成功',
    description: '學生預約成功後寄出；含取消驗證碼。請保留 {{cancellationCode}}。',
    channel: 'reservation',
    variables: [
      { name: 'studentName', description: '學生姓名', required: true },
      { name: 'studentId', description: '學號', required: true },
      { name: 'studentEmail', description: '收件信箱', required: true },
      { name: 'eventName', description: '活動名稱', required: true },
      { name: 'eventType', description: '活動類型' },
      { name: 'date', description: '日期' },
      { name: 'startTime', description: '開始時間' },
      { name: 'endTime', description: '結束時間' },
      { name: 'location', description: '地點（若有）' },
      { name: 'cancellationCode', description: '取消驗證碼', required: true },
    ],
    sampleData: {
      studentName: '王小明',
      studentId: 'B123456789',
      studentEmail: 'student@example.com',
      eventName: 'English Table 示範場',
      eventType: 'English Table',
      date: '2026-08-10',
      startTime: '12:10',
      endTime: '13:00',
      location: '圖書館討論室',
      cancellationCode: 'ABC123',
    },
  },
  {
    key: 'reservationCancellation',
    category: 'reservation',
    categoryLabel: '活動預約',
    name: '預約取消',
    description: '學生公開取消預約成功後寄出。',
    channel: 'reservation',
    variables: [
      { name: 'studentName', required: true },
      { name: 'studentId', required: true },
      { name: 'studentEmail', required: true },
      { name: 'eventName', required: true },
      { name: 'eventType' },
      { name: 'date' },
      { name: 'startTime' },
      { name: 'endTime' },
      { name: 'location' },
    ],
    sampleData: {
      studentName: '王小明',
      studentId: 'B123456789',
      studentEmail: 'student@example.com',
      eventName: 'English Table 示範場',
      eventType: 'English Table',
      date: '2026-08-10',
      startTime: '12:10',
      endTime: '13:00',
      location: '圖書館討論室',
    },
  },
  {
    key: 'waitlistJoined',
    category: 'reservation',
    categoryLabel: '活動預約',
    name: '候補成功',
    description: '加入候補名單成功。',
    channel: 'reservation',
    variables: [
      { name: 'studentName', required: true },
      { name: 'studentId', required: true },
      { name: 'studentEmail', required: true },
      { name: 'eventName', required: true },
      { name: 'eventType' },
      { name: 'date' },
      { name: 'startTime' },
      { name: 'endTime' },
      { name: 'waitlistPosition', description: '候補順位' },
    ],
    sampleData: {
      studentName: '王小明',
      studentId: 'B123456789',
      studentEmail: 'student@example.com',
      eventName: 'English Club 示範場',
      eventType: 'English Club',
      date: '2026-08-12',
      startTime: '18:00',
      endTime: '19:30',
      waitlistPosition: 3,
    },
  },
  {
    key: 'waitlistPromoted',
    category: 'reservation',
    categoryLabel: '活動預約',
    name: '候補轉正',
    description: '候補轉為正式預約；通常含取消驗證碼。',
    channel: 'reservation',
    variables: [
      { name: 'studentName', required: true },
      { name: 'studentId', required: true },
      { name: 'studentEmail', required: true },
      { name: 'eventName', required: true },
      { name: 'eventType' },
      { name: 'date' },
      { name: 'startTime' },
      { name: 'endTime' },
      { name: 'cancellationCode', required: true },
    ],
    sampleData: {
      studentName: '王小明',
      studentId: 'B123456789',
      studentEmail: 'student@example.com',
      eventName: 'English Club 示範場',
      eventType: 'English Club',
      date: '2026-08-12',
      startTime: '18:00',
      endTime: '19:30',
      cancellationCode: 'XYZ789',
    },
  },
  {
    key: 'blacklistNotification',
    category: 'reservation',
    categoryLabel: '活動預約',
    name: '黑名單通知',
    description: '違規累積進入黑名單後通知學生。',
    channel: 'reservation',
    variables: [
      { name: 'studentName', required: true },
      { name: 'studentId', required: true },
      { name: 'email', description: '收件信箱（此模板多用 email）', required: true },
      { name: 'unlockDate', description: '預計解封日' },
      { name: 'reason', description: '原因說明' },
    ],
    sampleData: {
      studentName: '王小明',
      studentId: 'B123456789',
      email: 'student@example.com',
      unlockDate: '2026-08-10',
      reason: '同學期違規達兩次',
    },
  },
  {
    key: 'englishTestEmailVerification',
    category: 'english_test',
    categoryLabel: '培力英檢',
    name: '信箱驗證碼（OTP）',
    description: '報名流程信箱驗證；請保留 {{code}}。',
    channel: 'bestep',
    variables: [
      { name: 'email', required: true },
      { name: 'code', description: '驗證碼', required: true },
      { name: 'expiresInMinutes', description: '有效分鐘數' },
    ],
    sampleData: {
      email: 'student@example.com',
      code: '123456',
      expiresInMinutes: 10,
    },
  },
  {
    key: 'englishTestRegistrationSuccess',
    category: 'english_test',
    categoryLabel: '培力英檢',
    name: '報名已送出（審核中）',
    description: '學生送出個人報名後的確認信。',
    channel: 'bestep',
    variables: [
      { name: 'name' },
      { name: 'studentNameZh' },
      { name: 'studentId', required: true },
      { name: 'email', required: true },
      { name: 'examType' },
      { name: 'status' },
      { name: 'registrationId' },
      { name: 'registrationDate' },
      { name: 'phone' },
    ],
    sampleData: {
      name: 'Wang Xiaoming',
      studentNameZh: '王小明',
      lastNameEn: 'Wang',
      firstNameEn: 'Xiaoming',
      studentId: 'B123456789',
      email: 'student@example.com',
      examType: 'LRSW',
      status: 'pending',
      registrationId: 1001,
      registrationDate: new Date().toISOString(),
      phone: '0912345678',
      idNumber: 'A123456789',
    },
  },
  {
    key: 'englishTestRegistrationRejected',
    category: 'english_test',
    categoryLabel: '培力英檢',
    name: '請修正',
    description: '審核改為「請修正」時寄出。',
    channel: 'bestep',
    variables: [
      { name: 'name' },
      { name: 'studentNameZh' },
      { name: 'studentId', required: true },
      { name: 'email', required: true },
      { name: 'rejectionReasons', description: '修正原因（字串或陣列）' },
      { name: 'examType' },
    ],
    sampleData: {
      name: 'Wang Xiaoming',
      studentNameZh: '王小明',
      lastNameEn: 'Wang',
      firstNameEn: 'Xiaoming',
      studentId: 'B123456789',
      email: 'student@example.com',
      examType: 'LR',
      rejectionReasons: '證件照模糊，請重新上傳',
      registrationId: 1001,
    },
  },
  {
    key: 'englishTestRegistrationFinalSuccess',
    category: 'english_test',
    categoryLabel: '培力英檢',
    name: '報名成功（最終）',
    description: '批次或手動寄「報名成功」信。',
    channel: 'bestep',
    variables: [
      { name: 'name' },
      { name: 'studentNameZh' },
      { name: 'studentId', required: true },
      { name: 'email', required: true },
      { name: 'examType' },
      { name: 'registrationId' },
      { name: 'registrationDate' },
      { name: 'phone' },
      { name: 'idNumber' },
    ],
    sampleData: {
      name: 'Wang Xiaoming',
      studentNameZh: '王小明',
      lastNameEn: 'Wang',
      firstNameEn: 'Xiaoming',
      studentId: 'B123456789',
      email: 'student@example.com',
      examType: 'LRSW',
      registrationId: 1001,
      registrationDate: new Date().toISOString(),
      phone: '0912345678',
      idNumber: 'A123456789',
    },
  },
  {
    key: 'englishTestRegistrationFinalFailure',
    category: 'english_test',
    categoryLabel: '培力英檢',
    name: '報名失敗（最終）',
    description: '狀態為報名失敗時寄出。',
    channel: 'bestep',
    variables: [
      { name: 'name' },
      { name: 'studentNameZh' },
      { name: 'studentId', required: true },
      { name: 'email', required: true },
      { name: 'examType' },
      { name: 'rejectionReasons' },
    ],
    sampleData: {
      name: 'Wang Xiaoming',
      studentNameZh: '王小明',
      lastNameEn: 'Wang',
      firstNameEn: 'Xiaoming',
      studentId: 'B123456789',
      email: 'student@example.com',
      examType: 'SW',
      rejectionReasons: '未於期限內完成修正',
      registrationId: 1001,
    },
  },
  {
    key: 'englishTestRegistrationGroupPromo',
    category: 'english_test',
    categoryLabel: '培力英檢',
    name: '團體報名推廣',
    description: '對符合條件者推廣學習有伴／團體報名。',
    channel: 'bestep',
    variables: [
      { name: 'name' },
      { name: 'studentNameZh' },
      { name: 'studentId', required: true },
      { name: 'email', required: true },
      { name: 'registrationShortLink', description: '團體報名連結' },
    ],
    sampleData: {
      name: 'Wang Xiaoming',
      studentNameZh: '王小明',
      lastNameEn: 'Wang',
      firstNameEn: 'Xiaoming',
      studentId: 'B123456789',
      email: 'student@example.com',
      registrationShortLink: 'https://example.com/learning-partner',
    },
  },
  {
    key: 'englishTestRegistrationUpdated',
    category: 'english_test',
    categoryLabel: '培力英檢',
    name: '學生已修正（通知行政）',
    description: '預設寄給行政信箱；收件人仍由程式決定。',
    channel: 'bestep',
    variables: [
      { name: 'name' },
      { name: 'studentNameZh' },
      { name: 'studentId', required: true },
      { name: 'email' },
      { name: 'examType' },
      { name: 'registrationId' },
    ],
    sampleData: {
      name: 'Wang Xiaoming',
      studentNameZh: '王小明',
      lastNameEn: 'Wang',
      firstNameEn: 'Xiaoming',
      studentId: 'B123456789',
      email: 'student@example.com',
      examType: 'LR',
      registrationId: 1001,
    },
  },
  {
    key: 'englishTestRegistrationModificationComplete',
    category: 'english_test',
    categoryLabel: '培力英檢',
    name: '修正完成（通知學生）',
    description: '學生完成修正後寄給學生。',
    channel: 'bestep',
    variables: [
      { name: 'name' },
      { name: 'studentNameZh' },
      { name: 'studentId', required: true },
      { name: 'email', required: true },
      { name: 'examType' },
    ],
    sampleData: {
      name: 'Wang Xiaoming',
      studentNameZh: '王小明',
      lastNameEn: 'Wang',
      firstNameEn: 'Xiaoming',
      studentId: 'B123456789',
      email: 'student@example.com',
      examType: 'LR',
      registrationId: 1001,
    },
  },
  {
    key: 'learningPartnerInvitation',
    category: 'learning_partner',
    categoryLabel: '學習有伴',
    name: '團體邀請',
    description: '邀請成員加入團體報名。',
    channel: 'bestep',
    variables: [
      { name: 'name', description: '成員姓名' },
      { name: 'email', required: true },
      { name: 'studentId' },
      { name: 'teamId' },
      { name: 'teamName' },
      { name: 'teamSize' },
      { name: 'memberList' },
      { name: 'approvalLink', description: '同意連結' },
      { name: 'expiresAt' },
      { name: 'expiresAtHours' },
    ],
    sampleData: {
      name: '陳小華',
      email: 'member@example.com',
      studentId: 'B987654321',
      teamId: 'TEAM-001',
      teamName: '英語練習小組',
      teamSize: 3,
      memberList: '1. 王小明\n2. 陳小華\n3. 林小美',
      approvalLink: 'https://example.com/invite/abc',
      expiresAt: '2026-08-04 18:00',
      expiresAtHours: 24,
    },
  },
  {
    key: 'learningPartnerInvitationResend',
    category: 'learning_partner',
    categoryLabel: '學習有伴',
    name: '重寄邀請',
    description: '重新寄出團體邀請。',
    channel: 'bestep',
    variables: [
      { name: 'name' },
      { name: 'email', required: true },
      { name: 'studentId' },
      { name: 'teamId' },
      { name: 'teamName' },
      { name: 'teamSize' },
      { name: 'memberList' },
      { name: 'approvalLink' },
      { name: 'expiresAt' },
      { name: 'expiresAtHours' },
    ],
    sampleData: {
      name: '陳小華',
      email: 'member@example.com',
      studentId: 'B987654321',
      teamId: 'TEAM-001',
      teamName: '英語練習小組',
      teamSize: 3,
      memberList: '1. 王小明\n2. 陳小華\n3. 林小美',
      approvalLink: 'https://example.com/invite/abc',
      expiresAt: '2026-08-04 18:00',
      expiresAtHours: 24,
    },
  },
  {
    key: 'learningPartnerAllApproved',
    category: 'learning_partner',
    categoryLabel: '學習有伴',
    name: '全員同意完成',
    description: '團體所有成員同意後通知。',
    channel: 'bestep',
    variables: [
      { name: 'name' },
      { name: 'email', required: true },
      { name: 'studentId' },
      { name: 'teamId' },
      { name: 'teamName' },
      { name: 'memberList' },
    ],
    sampleData: {
      name: '陳小華',
      email: 'member@example.com',
      studentId: 'B987654321',
      teamId: 'TEAM-001',
      teamName: '英語練習小組',
      memberList: '1. 王小明\n2. 陳小華\n3. 林小美',
    },
  },
  {
    key: 'learningPartnerCancelled',
    category: 'learning_partner',
    categoryLabel: '學習有伴',
    name: '團體取消',
    description: '管理員取消團體時通知。',
    channel: 'bestep',
    variables: [
      { name: 'name' },
      { name: 'email', required: true },
      { name: 'studentId' },
      { name: 'teamId' },
      { name: 'teamName' },
      { name: 'reason' },
    ],
    sampleData: {
      name: '陳小華',
      email: 'member@example.com',
      studentId: 'B987654321',
      teamId: 'TEAM-001',
      teamName: '英語練習小組',
      reason: '成員不足',
    },
  },
  {
    key: 'learningPartnerExpired',
    category: 'learning_partner',
    categoryLabel: '學習有伴',
    name: '團體逾期（預留）',
    description: '模板已定義；目前可能尚未自動觸發寄信。',
    channel: 'bestep',
    variables: [
      { name: 'name' },
      { name: 'email', required: true },
      { name: 'studentId' },
      { name: 'teamId' },
      { name: 'teamName' },
    ],
    sampleData: {
      name: '陳小華',
      email: 'member@example.com',
      studentId: 'B987654321',
      teamId: 'TEAM-001',
      teamName: '英語練習小組',
    },
  },
];

const CATALOG_BY_KEY = Object.fromEntries(EMAIL_TEMPLATE_CATALOG.map((t) => [t.key, t]));

function listEmailTemplateCatalog() {
  return EMAIL_TEMPLATE_CATALOG.map(({ sampleData, ...rest }) => rest);
}

function getEmailTemplateCatalogEntry(key) {
  return CATALOG_BY_KEY[key] || null;
}

function getEmailTemplateSampleData(key) {
  const entry = CATALOG_BY_KEY[key];
  return entry ? { ...entry.sampleData } : null;
}

module.exports = {
  EMAIL_TEMPLATE_CATALOG,
  listEmailTemplateCatalog,
  getEmailTemplateCatalogEntry,
  getEmailTemplateSampleData,
};
