// utils/postalCodeMap.js
// 台灣郵遞區號對應縣市和行政區的對應表
// 資料來源：中華郵政公司

const postalCodeMap = {
  // 台北市
  '100': { city: '台北市', district: '中正區' },
  '103': { city: '台北市', district: '大同區' },
  '104': { city: '台北市', district: '中山區' },
  '105': { city: '台北市', district: '松山區' },
  '106': { city: '台北市', district: '大安區' },
  '108': { city: '台北市', district: '萬華區' },
  '110': { city: '台北市', district: '信義區' },
  '111': { city: '台北市', district: '士林區' },
  '112': { city: '台北市', district: '北投區' },
  '114': { city: '台北市', district: '內湖區' },
  '115': { city: '台北市', district: '南港區' },
  '116': { city: '台北市', district: '文山區' },
  
  // 新北市
  '207': { city: '新北市', district: '萬里區' },
  '208': { city: '新北市', district: '金山區' },
  '220': { city: '新北市', district: '板橋區' },
  '221': { city: '新北市', district: '汐止區' },
  '222': { city: '新北市', district: '深坑區' },
  '223': { city: '新北市', district: '石碇區' },
  '224': { city: '新北市', district: '瑞芳區' },
  '226': { city: '新北市', district: '平溪區' },
  '227': { city: '新北市', district: '雙溪區' },
  '228': { city: '新北市', district: '貢寮區' },
  '231': { city: '新北市', district: '新店區' },
  '232': { city: '新北市', district: '坪林區' },
  '233': { city: '新北市', district: '烏來區' },
  '234': { city: '新北市', district: '永和區' },
  '235': { city: '新北市', district: '中和區' },
  '236': { city: '新北市', district: '土城區' },
  '237': { city: '新北市', district: '三峽區' },
  '238': { city: '新北市', district: '樹林區' },
  '239': { city: '新北市', district: '鶯歌區' },
  '241': { city: '新北市', district: '三重區' },
  '242': { city: '新北市', district: '新莊區' },
  '243': { city: '新北市', district: '泰山區' },
  '244': { city: '新北市', district: '林口區' },
  '247': { city: '新北市', district: '蘆洲區' },
  '248': { city: '新北市', district: '五股區' },
  '249': { city: '新北市', district: '八里區' },
  '251': { city: '新北市', district: '淡水區' },
  '252': { city: '新北市', district: '三芝區' },
  '253': { city: '新北市', district: '石門區' },
  
  // 桃園市
  '320': { city: '桃園市', district: '中壢區' },
  '324': { city: '桃園市', district: '平鎮區' },
  '325': { city: '桃園市', district: '龍潭區' },
  '326': { city: '桃園市', district: '楊梅區' },
  '327': { city: '桃園市', district: '新屋區' },
  '328': { city: '桃園市', district: '觀音區' },
  '330': { city: '桃園市', district: '桃園區' },
  '333': { city: '桃園市', district: '龜山區' },
  '334': { city: '桃園市', district: '八德區' },
  '335': { city: '桃園市', district: '大溪區' },
  '336': { city: '桃園市', district: '復興區' },
  '337': { city: '桃園市', district: '大園區' },
  '338': { city: '桃園市', district: '蘆竹區' },
  
  // 新竹市（300 對應多個區，預設填入東區，用戶可手動修改）
  '300': { city: '新竹市', district: '東區' },
  
  // 新竹縣
  '302': { city: '新竹縣', district: '竹北市' },
  '303': { city: '新竹縣', district: '湖口鄉' },
  '304': { city: '新竹縣', district: '新豐鄉' },
  '305': { city: '新竹縣', district: '新埔鎮' },
  '306': { city: '新竹縣', district: '關西鎮' },
  '307': { city: '新竹縣', district: '芎林鄉' },
  '308': { city: '新竹縣', district: '寶山鄉' },
  '310': { city: '新竹縣', district: '竹東鎮' },
  '311': { city: '新竹縣', district: '五峰鄉' },
  '312': { city: '新竹縣', district: '橫山鄉' },
  '313': { city: '新竹縣', district: '尖石鄉' },
  '314': { city: '新竹縣', district: '北埔鄉' },
  '315': { city: '新竹縣', district: '峨眉鄉' },
  
  // 苗栗縣
  '350': { city: '苗栗縣', district: '竹南鎮' },
  '351': { city: '苗栗縣', district: '頭份市' },
  '352': { city: '苗栗縣', district: '三灣鄉' },
  '353': { city: '苗栗縣', district: '南庄鄉' },
  '354': { city: '苗栗縣', district: '獅潭鄉' },
  '356': { city: '苗栗縣', district: '後龍鎮' },
  '357': { city: '苗栗縣', district: '通霄鎮' },
  '358': { city: '苗栗縣', district: '苑裡鎮' },
  '360': { city: '苗栗縣', district: '苗栗市' },
  '361': { city: '苗栗縣', district: '造橋鄉' },
  '362': { city: '苗栗縣', district: '頭屋鄉' },
  '363': { city: '苗栗縣', district: '公館鄉' },
  '364': { city: '苗栗縣', district: '大湖鄉' },
  '365': { city: '苗栗縣', district: '泰安鄉' },
  '366': { city: '苗栗縣', district: '銅鑼鄉' },
  '367': { city: '苗栗縣', district: '三義鄉' },
  '368': { city: '苗栗縣', district: '西湖鄉' },
  '369': { city: '苗栗縣', district: '卓蘭鎮' },
  
  // 台中市
  '400': { city: '台中市', district: '中區' },
  '401': { city: '台中市', district: '東區' },
  '402': { city: '台中市', district: '南區' },
  '403': { city: '台中市', district: '西區' },
  '404': { city: '台中市', district: '北區' },
  '406': { city: '台中市', district: '北屯區' },
  '407': { city: '台中市', district: '西屯區' },
  '408': { city: '台中市', district: '南屯區' },
  '411': { city: '台中市', district: '太平區' },
  '412': { city: '台中市', district: '大里區' },
  '413': { city: '台中市', district: '霧峰區' },
  '414': { city: '台中市', district: '烏日區' },
  '420': { city: '台中市', district: '豐原區' },
  '421': { city: '台中市', district: '后里區' },
  '422': { city: '台中市', district: '石岡區' },
  '423': { city: '台中市', district: '東勢區' },
  '424': { city: '台中市', district: '和平區' },
  '426': { city: '台中市', district: '新社區' },
  '427': { city: '台中市', district: '潭子區' },
  '428': { city: '台中市', district: '大雅區' },
  '429': { city: '台中市', district: '神岡區' },
  '432': { city: '台中市', district: '大肚區' },
  '433': { city: '台中市', district: '沙鹿區' },
  '434': { city: '台中市', district: '龍井區' },
  '435': { city: '台中市', district: '梧棲區' },
  '436': { city: '台中市', district: '清水區' },
  '437': { city: '台中市', district: '大甲區' },
  '438': { city: '台中市', district: '外埔區' },
  '439': { city: '台中市', district: '大安區' },
  
  // 彰化縣
  '500': { city: '彰化縣', district: '彰化市' },
  '502': { city: '彰化縣', district: '芬園鄉' },
  '503': { city: '彰化縣', district: '花壇鄉' },
  '504': { city: '彰化縣', district: '秀水鄉' },
  '505': { city: '彰化縣', district: '鹿港鎮' },
  '506': { city: '彰化縣', district: '福興鄉' },
  '507': { city: '彰化縣', district: '線西鄉' },
  '508': { city: '彰化縣', district: '和美鎮' },
  '509': { city: '彰化縣', district: '伸港鄉' },
  '510': { city: '彰化縣', district: '員林市' },
  '511': { city: '彰化縣', district: '社頭鄉' },
  '512': { city: '彰化縣', district: '永靖鄉' },
  '513': { city: '彰化縣', district: '埔心鄉' },
  '514': { city: '彰化縣', district: '溪湖鎮' },
  '515': { city: '彰化縣', district: '大村鄉' },
  '516': { city: '彰化縣', district: '埔鹽鄉' },
  '520': { city: '彰化縣', district: '田中鎮' },
  '521': { city: '彰化縣', district: '北斗鎮' },
  '522': { city: '彰化縣', district: '田尾鄉' },
  '523': { city: '彰化縣', district: '埤頭鄉' },
  '524': { city: '彰化縣', district: '溪州鄉' },
  '525': { city: '彰化縣', district: '竹塘鄉' },
  '526': { city: '彰化縣', district: '二林鎮' },
  '527': { city: '彰化縣', district: '大城鄉' },
  '528': { city: '彰化縣', district: '芳苑鄉' },
  '530': { city: '彰化縣', district: '二水鄉' },
  
  // 南投縣
  '540': { city: '南投縣', district: '南投市' },
  '541': { city: '南投縣', district: '中寮鄉' },
  '542': { city: '南投縣', district: '草屯鎮' },
  '544': { city: '南投縣', district: '國姓鄉' },
  '545': { city: '南投縣', district: '埔里鎮' },
  '546': { city: '南投縣', district: '仁愛鄉' },
  '551': { city: '南投縣', district: '名間鄉' },
  '552': { city: '南投縣', district: '集集鎮' },
  '553': { city: '南投縣', district: '水里鄉' },
  '555': { city: '南投縣', district: '魚池鄉' },
  '556': { city: '南投縣', district: '信義鄉' },
  '557': { city: '南投縣', district: '竹山鎮' },
  '558': { city: '南投縣', district: '鹿谷鄉' },
  
  // 雲林縣
  '630': { city: '雲林縣', district: '斗南鎮' },
  '631': { city: '雲林縣', district: '大埤鄉' },
  '632': { city: '雲林縣', district: '虎尾鎮' },
  '633': { city: '雲林縣', district: '土庫鎮' },
  '634': { city: '雲林縣', district: '褒忠鄉' },
  '635': { city: '雲林縣', district: '東勢鄉' },
  '636': { city: '雲林縣', district: '台西鄉' },
  '637': { city: '雲林縣', district: '崙背鄉' },
  '638': { city: '雲林縣', district: '麥寮鄉' },
  '640': { city: '雲林縣', district: '斗六市' },
  '643': { city: '雲林縣', district: '林內鄉' },
  '646': { city: '雲林縣', district: '古坑鄉' },
  '647': { city: '雲林縣', district: '莿桐鄉' },
  '648': { city: '雲林縣', district: '西螺鎮' },
  '649': { city: '雲林縣', district: '二崙鄉' },
  '651': { city: '雲林縣', district: '北港鎮' },
  '652': { city: '雲林縣', district: '水林鄉' },
  '653': { city: '雲林縣', district: '口湖鄉' },
  '654': { city: '雲林縣', district: '四湖鄉' },
  '655': { city: '雲林縣', district: '元長鄉' },
  
  // 嘉義市（600 對應多個區，預設填入東區，用戶可手動修改）
  '600': { city: '嘉義市', district: '東區' },
  
  // 嘉義縣
  '602': { city: '嘉義縣', district: '番路鄉' },
  '603': { city: '嘉義縣', district: '梅山鄉' },
  '604': { city: '嘉義縣', district: '竹崎鄉' },
  '605': { city: '嘉義縣', district: '阿里山鄉' },
  '606': { city: '嘉義縣', district: '中埔鄉' },
  '607': { city: '嘉義縣', district: '大埔鄉' },
  '608': { city: '嘉義縣', district: '水上鄉' },
  '611': { city: '嘉義縣', district: '鹿草鄉' },
  '612': { city: '嘉義縣', district: '太保市' },
  '613': { city: '嘉義縣', district: '朴子市' },
  '614': { city: '嘉義縣', district: '東石鄉' },
  '615': { city: '嘉義縣', district: '六腳鄉' },
  '616': { city: '嘉義縣', district: '新港鄉' },
  '621': { city: '嘉義縣', district: '民雄鄉' },
  '622': { city: '嘉義縣', district: '大林鎮' },
  '623': { city: '嘉義縣', district: '溪口鄉' },
  '624': { city: '嘉義縣', district: '義竹鄉' },
  '625': { city: '嘉義縣', district: '布袋鎮' },
  
  // 台南市
  '700': { city: '台南市', district: '中西區' },
  '701': { city: '台南市', district: '東區' },
  '702': { city: '台南市', district: '南區' },
  '704': { city: '台南市', district: '北區' },
  '708': { city: '台南市', district: '安平區' },
  '709': { city: '台南市', district: '安南區' },
  '710': { city: '台南市', district: '永康區' },
  '711': { city: '台南市', district: '歸仁區' },
  '712': { city: '台南市', district: '新化區' },
  '713': { city: '台南市', district: '左鎮區' },
  '714': { city: '台南市', district: '玉井區' },
  '715': { city: '台南市', district: '楠西區' },
  '716': { city: '台南市', district: '南化區' },
  '717': { city: '台南市', district: '仁德區' },
  '718': { city: '台南市', district: '關廟區' },
  '719': { city: '台南市', district: '龍崎區' },
  '720': { city: '台南市', district: '官田區' },
  '721': { city: '台南市', district: '麻豆區' },
  '722': { city: '台南市', district: '佳里區' },
  '723': { city: '台南市', district: '西港區' },
  '724': { city: '台南市', district: '七股區' },
  '725': { city: '台南市', district: '將軍區' },
  '726': { city: '台南市', district: '學甲區' },
  '727': { city: '台南市', district: '北門區' },
  '730': { city: '台南市', district: '新營區' },
  '731': { city: '台南市', district: '後壁區' },
  '732': { city: '台南市', district: '白河區' },
  '733': { city: '台南市', district: '東山區' },
  '734': { city: '台南市', district: '六甲區' },
  '735': { city: '台南市', district: '下營區' },
  '736': { city: '台南市', district: '柳營區' },
  '737': { city: '台南市', district: '鹽水區' },
  '741': { city: '台南市', district: '善化區' },
  '742': { city: '台南市', district: '大內區' },
  '743': { city: '台南市', district: '山上區' },
  '744': { city: '台南市', district: '新市區' },
  '745': { city: '台南市', district: '安定區' },
  
  // 高雄市
  '800': { city: '高雄市', district: '新興區' },
  '801': { city: '高雄市', district: '前金區' },
  '802': { city: '高雄市', district: '苓雅區' },
  '803': { city: '高雄市', district: '鹽埕區' },
  '804': { city: '高雄市', district: '鼓山區' },
  '805': { city: '高雄市', district: '旗津區' },
  '806': { city: '高雄市', district: '前鎮區' },
  '807': { city: '高雄市', district: '三民區' },
  '811': { city: '高雄市', district: '楠梓區' },
  '812': { city: '高雄市', district: '小港區' },
  '813': { city: '高雄市', district: '左營區' },
  '814': { city: '高雄市', district: '仁武區' },
  '815': { city: '高雄市', district: '大社區' },
  '820': { city: '高雄市', district: '岡山區' },
  '821': { city: '高雄市', district: '路竹區' },
  '822': { city: '高雄市', district: '阿蓮區' },
  '823': { city: '高雄市', district: '田寮區' },
  '824': { city: '高雄市', district: '燕巢區' },
  '825': { city: '高雄市', district: '橋頭區' },
  '826': { city: '高雄市', district: '梓官區' },
  '827': { city: '高雄市', district: '彌陀區' },
  '828': { city: '高雄市', district: '永安區' },
  '829': { city: '高雄市', district: '湖內區' },
  '830': { city: '高雄市', district: '鳳山區' },
  '831': { city: '高雄市', district: '大寮區' },
  '832': { city: '高雄市', district: '林園區' },
  '833': { city: '高雄市', district: '鳥松區' },
  '840': { city: '高雄市', district: '大樹區' },
  '842': { city: '高雄市', district: '旗山區' },
  '843': { city: '高雄市', district: '美濃區' },
  '844': { city: '高雄市', district: '六龜區' },
  '845': { city: '高雄市', district: '內門區' },
  '846': { city: '高雄市', district: '杉林區' },
  '847': { city: '高雄市', district: '甲仙區' },
  '848': { city: '高雄市', district: '桃源區' },
  '849': { city: '高雄市', district: '那瑪夏區' },
  '851': { city: '高雄市', district: '茂林區' },
  '852': { city: '高雄市', district: '茄萣區' },
  
  // 屏東縣
  '900': { city: '屏東縣', district: '屏東市' },
  '901': { city: '屏東縣', district: '三地門鄉' },
  '902': { city: '屏東縣', district: '霧台鄉' },
  '903': { city: '屏東縣', district: '瑪家鄉' },
  '904': { city: '屏東縣', district: '九如鄉' },
  '905': { city: '屏東縣', district: '里港鄉' },
  '906': { city: '屏東縣', district: '高樹鄉' },
  '907': { city: '屏東縣', district: '鹽埔鄉' },
  '908': { city: '屏東縣', district: '長治鄉' },
  '909': { city: '屏東縣', district: '麟洛鄉' },
  '911': { city: '屏東縣', district: '竹田鄉' },
  '912': { city: '屏東縣', district: '內埔鄉' },
  '913': { city: '屏東縣', district: '萬丹鄉' },
  '920': { city: '屏東縣', district: '潮州鎮' },
  '921': { city: '屏東縣', district: '泰武鄉' },
  '922': { city: '屏東縣', district: '來義鄉' },
  '923': { city: '屏東縣', district: '萬巒鄉' },
  '924': { city: '屏東縣', district: '崁頂鄉' },
  '925': { city: '屏東縣', district: '新埤鄉' },
  '926': { city: '屏東縣', district: '南州鄉' },
  '927': { city: '屏東縣', district: '林邊鄉' },
  '928': { city: '屏東縣', district: '東港鎮' },
  '929': { city: '屏東縣', district: '琉球鄉' },
  '931': { city: '屏東縣', district: '佳冬鄉' },
  '932': { city: '屏東縣', district: '新園鄉' },
  '940': { city: '屏東縣', district: '枋寮鄉' },
  '941': { city: '屏東縣', district: '枋山鄉' },
  '942': { city: '屏東縣', district: '春日鄉' },
  '943': { city: '屏東縣', district: '獅子鄉' },
  '944': { city: '屏東縣', district: '車城鄉' },
  '945': { city: '屏東縣', district: '牡丹鄉' },
  '946': { city: '屏東縣', district: '恆春鎮' },
  '947': { city: '屏東縣', district: '滿州鄉' },
  
  // 台東縣
  '950': { city: '台東縣', district: '台東市' },
  '951': { city: '台東縣', district: '綠島鄉' },
  '952': { city: '台東縣', district: '蘭嶼鄉' },
  '953': { city: '台東縣', district: '延平鄉' },
  '954': { city: '台東縣', district: '卑南鄉' },
  '955': { city: '台東縣', district: '鹿野鄉' },
  '956': { city: '台東縣', district: '關山鎮' },
  '957': { city: '台東縣', district: '海端鄉' },
  '958': { city: '台東縣', district: '池上鄉' },
  '959': { city: '台東縣', district: '東河鄉' },
  '961': { city: '台東縣', district: '成功鎮' },
  '962': { city: '台東縣', district: '長濱鄉' },
  '963': { city: '台東縣', district: '太麻里鄉' },
  '964': { city: '台東縣', district: '金峰鄉' },
  '965': { city: '台東縣', district: '大武鄉' },
  '966': { city: '台東縣', district: '達仁鄉' },
  
  // 花蓮縣
  '970': { city: '花蓮縣', district: '花蓮市' },
  '971': { city: '花蓮縣', district: '新城鄉' },
  '972': { city: '花蓮縣', district: '太魯閣' },
  '973': { city: '花蓮縣', district: '秀林鄉' },
  '974': { city: '花蓮縣', district: '吉安鄉' },
  '975': { city: '花蓮縣', district: '壽豐鄉' },
  '976': { city: '花蓮縣', district: '鳳林鎮' },
  '977': { city: '花蓮縣', district: '光復鄉' },
  '978': { city: '花蓮縣', district: '豐濱鄉' },
  '979': { city: '花蓮縣', district: '瑞穗鄉' },
  '981': { city: '花蓮縣', district: '玉里鎮' },
  '982': { city: '花蓮縣', district: '卓溪鄉' },
  '983': { city: '花蓮縣', district: '富里鄉' },
  
  // 澎湖縣
  '880': { city: '澎湖縣', district: '馬公市' },
  '881': { city: '澎湖縣', district: '西嶼鄉' },
  '882': { city: '澎湖縣', district: '望安鄉' },
  '883': { city: '澎湖縣', district: '七美鄉' },
  '884': { city: '澎湖縣', district: '白沙鄉' },
  '885': { city: '澎湖縣', district: '湖西鄉' },
  
  // 金門縣
  '890': { city: '金門縣', district: '金沙鎮' },
  '891': { city: '金門縣', district: '金湖鎮' },
  '892': { city: '金門縣', district: '金寧鄉' },
  '893': { city: '金門縣', district: '金城鎮' },
  '894': { city: '金門縣', district: '烈嶼鄉' },
  '896': { city: '金門縣', district: '烏坵鄉' },
  
  // 連江縣
  '209': { city: '連江縣', district: '南竿鄉' },
  '210': { city: '連江縣', district: '北竿鄉' },
  '211': { city: '連江縣', district: '莒光鄉' },
  '212': { city: '連江縣', district: '東引鄉' },
  
  // 基隆市
  '200': { city: '基隆市', district: '仁愛區' },
  '201': { city: '基隆市', district: '信義區' },
  '202': { city: '基隆市', district: '中正區' },
  '203': { city: '基隆市', district: '中山區' },
  '204': { city: '基隆市', district: '安樂區' },
  '205': { city: '基隆市', district: '暖暖區' },
  '206': { city: '基隆市', district: '七堵區' },
  
  // 宜蘭縣
  '260': { city: '宜蘭縣', district: '宜蘭市' },
  '261': { city: '宜蘭縣', district: '頭城鎮' },
  '262': { city: '宜蘭縣', district: '礁溪鄉' },
  '263': { city: '宜蘭縣', district: '壯圍鄉' },
  '264': { city: '宜蘭縣', district: '員山鄉' },
  '265': { city: '宜蘭縣', district: '羅東鎮' },
  '266': { city: '宜蘭縣', district: '三星鄉' },
  '267': { city: '宜蘭縣', district: '大同鄉' },
  '268': { city: '宜蘭縣', district: '五結鄉' },
  '269': { city: '宜蘭縣', district: '冬山鄉' },
  '270': { city: '宜蘭縣', district: '蘇澳鎮' },
  '272': { city: '宜蘭縣', district: '南澳鄉' },
};

// 根據郵遞區號查詢縣市和行政區
export function getCityDistrictByPostalCode(postalCode) {
  if (!postalCode || postalCode.length !== 3) {
    return null;
  }
  
  const code = String(postalCode).trim();
  return postalCodeMap[code] || null;
}

export default postalCodeMap;
